/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ActivitiesIndexImport } from './routes/activities/index'
import { Route as ActivitiesActivityIdImport } from './routes/activities/$activityId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ActivitiesIndexRoute = ActivitiesIndexImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRoute,
} as any)

const ActivitiesActivityIdRoute = ActivitiesActivityIdImport.update({
  id: '/activities/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/activities/$activityId': {
      id: '/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdImport
      parentRoute: typeof rootRoute
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities': typeof ActivitiesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities': typeof ActivitiesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/': typeof ActivitiesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activities/$activityId' | '/activities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activities/$activityId' | '/activities'
  id: '__root__' | '/' | '/activities/$activityId' | '/activities/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/activities/$activityId",
        "/activities/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/activities/$activityId": {
      "filePath": "activities/$activityId.tsx"
    },
    "/activities/": {
      "filePath": "activities/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
